name: Pull Request CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yaml
    with:
      RUN_TEST: true
      NODE_VERSION_MATRIX: "['20.x', '22.x']"
      ARTIFACT: false