name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  preRelease:
    name: PreRelease
    runs-on: ubuntu-latest
    outputs:
      hasChangesets: ${{ steps.changesets.outputs.hasChangesets }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm ci
      - name: Create Release Pull Request
        id: changesets
        uses: changesets/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: Release PR
          commit: "release"
  build:
    name: Build
    needs: preRelease
    if: needs.preRelease.outputs.hasChangesets == 'false'
    uses: ./.github/workflows/build.yaml
    with:
      RUN_TEST: false
      NODE_VERSION_MATRIX: "['22.x']"
      ARTIFACT: true
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build
    if: needs.preRelease.outputs.hasChangesets == 'false'
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: build
          path: dist
      - run: npm ci
      - name: Release
        id: changesets
        uses: changesets/action@v1
        with:
          publish: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
